/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-si446x
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SI446X_API_H
#define INCLUDED_SI446X_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_si446x_EXPORTS
#define SI446X_API __GR_ATTR_EXPORT
#else
#define SI446X_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SI446X_API_H */
